services:

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - local_network
    restart: always

  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - site:/var/www/html/:ro
    networks:
      - local_network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    volumes:
      - site:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - local_network
    restart: always


volumes:

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/scambier/data/database

  site:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/scambier/data/site


networks:

  local_network:
    driver: bridge
